services:
  - type: web
    name: sea-market-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flet run app.py --web --port $PORT --host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0